import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";

// "/" is intentionally included so the deployed root URL shows a public
// landing page (`src/components/Landing.tsx`, rendered by
// `src/app/page.tsx` when signed out) instead of bouncing every visitor to
// `/login` with zero explanation of the product. This does NOT open the
// rest of the app: `isPublicPath`'s prefix check below is
// `startsWith(\`${p}/\`)`, and for `p = "/"` that's `startsWith("//")` —
// true only for paths starting with a literal double slash, which no real
// route has. So `"/"` matches the root path exactly and nothing else
// (`/holdings`, `/settings`, etc. still require auth). Don't copy this
// prefix-check pattern for any other path — it only stays safe here because
// "/" is the one string where the prefix form can't accidentally widen.
const PUBLIC_PATHS = [
  "/",
  "/login",
  "/auth",
  "/privacy",
  "/terms",
  "/demo",
  "/api/demo",
  // Generated by src/app/robots.ts / src/app/sitemap.ts — the proxy matcher
  // in src/proxy.ts doesn't exclude these paths, so without this they'd
  // redirect every signed-out crawler to /login instead of serving content.
  "/robots.txt",
  "/sitemap.xml",
];

function isPublicPath(pathname: string): boolean {
  return PUBLIC_PATHS.some((p) => pathname === p || pathname.startsWith(`${p}/`));
}

export async function updateSession(request: NextRequest) {
  let supabaseResponse = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          supabaseResponse = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options)
          );
        },
      },
    }
  );

  // Do not run code between createServerClient and getClaims() — see
  // https://supabase.com/docs/guides/auth/server-side/nextjs, this refresh
  // is what keeps users from being randomly logged out.
  const { data } = await supabase.auth.getClaims();
  const isAuthed = data?.claims != null;
  const { pathname } = request.nextUrl;

  if (!isAuthed && !isPublicPath(pathname)) {
    const url = request.nextUrl.clone();
    url.pathname = "/login";
    return NextResponse.redirect(url);
  }

  if (isAuthed && pathname === "/login") {
    const url = request.nextUrl.clone();
    url.pathname = "/";
    return NextResponse.redirect(url);
  }

  return supabaseResponse;
}
